Repository traceroot-ai/traceroot, pull requests merged in 2025-08, with the labels that each got.

#91 changes for the dark mode ui changes
  ui/src/app/page.tsx
  ui/src/components/explore/Trace.tsx
  ui/src/components/right-panel/agent/Agent.tsx
  ui/src/components/right-panel/agent/MessageInput.tsx
  ui/src/components/side-bar/Sidebar.tsx
Labels: bug, ui

#94 Apply some fixes
  rest/utils/constants.py
  rest/utils/log.py
  test/utils/test_log.py
  ui/src/app/api/autumn/[...all]/route.ts
Labels: bug

#116 Fix searchbar metadata
  ui/src/components/explore/SearchBar.tsx
Labels: bug, ui

#119 feat: Make log search by default and highlight search terms #139
  ui/src/app/explore/page.tsx
  ui/src/components/explore/SearchBar.tsx
  ui/src/components/explore/Trace.tsx
  ui/src/components/right-panel/RightPanelSwitch.tsx
  ui/src/components/right-panel/log/LogDetail.tsx
  ui/src/components/right-panel/log/LogPanelSwitch.tsx
Labels: enhancement, feature
